services:
  postgres:
    image: postgres:15
    container_name: kasparro_postgres
    environment:
      POSTGRES_USER: kasparro
      POSTGRES_PASSWORD: kasparro
      POSTGRES_DB: kasparro_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: kasparro_api
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://kasparro:kasparro@postgres:5432/kasparro_db

volumes:
  pg_data:
